config/routes.rb
Advising::Application.routes.draw do
  resources :messages
  get  'message' => 'messages#index'
  post 'message' => 'messages#index'
  
  controller :messages do
    get 'message' => :index
    get  'message' => 'messages#index'
    post 'message' => 'messages#index'
  end
  
    post 'admin' => 'admin#regstudent'

  resources :appointments
  post '/createappt' => 'appointments#createAppt'
  post 'delappt' => 'appointments#destroy'
  post 'schdappt' => 'appointments#schdappt'
  get '/createappt' => 'appointments#createAppt'
  get 'delappt' => 'appointments#destroy'
  get 'schdappt' => 'appointments#schdappt'
  post 'cancappt' => 'appointments#cancappt'
  get 'viewAppts' => 'users#viewAppts'
  post 'setAppt' => 'appointments#setAppt'
  get 'denyApt' => 'appointments#deny'
  get 'approveApt' => 'appointments#approve'
  get 'deleteApt' => 'appointments#destroy'
  
  resources :courselists
  post 'getcourse' => 'courses#getcourse'
  post 'setAppt' => 'courses#setAppt'
  get 'getcourse' => 'courses#getcourse'
  post 'contactf' => 'courses#contactf'
  get 'contactf' => 'courses#contactf'

  post 'testajaxjs' => 'courses#testajaxjs'

  resources :courses
  get "student/index"
  get 'admin' => 'admin#index'
  get 'advisor' => 'advisor#index'
  get 'student' => 'student#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get "admin/index"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :users
  post 'liftFlag' => 'users#liftFlag'
  get 'liftFlag' => 'users#liftFlag'
  post 'destroy' => 'users#destroy'
  post 'denyFlag' => 'users#denyFlag'
  get 'denyFlag' => 'users#denyFlag'
  get  'messagee' => 'messages#index'#hitting this one

  controller :users do
    post 'liftFlag' => :liftFlag
    get  'liftFlag' => :liftFlag
    post 'denyFlag' => :denyFlag
    get  'denyFlag' => :denyFlag
  end
  
  resources :users do
    resources :courses
  end
  

  root 'sessions#new', as: 'advising'
  root :to =>'sessions#new'
  
  
  
  

end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  layout 'menu'
  def index
  end
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/student/_courselist_modal.html.erb
<div class="modal fade" id='<%= "courselistModal_#{user.id}" %>' tabindex="-1" role="dialog" aria-labelledby="courselistModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-title" id="courselistModalLabel" style="color: black">Course Catalog</h2>
			</div>
			<div class="modal-body">
				<% @courselists = Courselist.all %>
				<% @currentuser = User.find_by_id(session[:user_id]) %>
				<% @courses =  Course.all%>
				<% @total = 0%>
				<% @takencourse = 0%>
				<% @flag = 0%>

				<% if @currentuser.classification == "Student" %>
				<br>
				<div style="border:solid; border-color: white; scroll; height:57%; overflow-x:hidden;background: rgba(255,255,255,0.1);">
					<table class="table table-bordered">
						<thead >
							<tr style="height:50px; color:black">
								<th>Name</th>
								<th>Prereq</th>
								<th>Hours</th>
								<th>Description</th>
								<th>Completion</th>
							</tr>
						</thead>
						<tbody>
							<% @courselists.each do |courselist| %>
							<% @total = @total+1%>
							<% @courses.each do |course|%>
							<%if course.studentid == @currentuser.id && courselist.name==course.name%>
							<% @takencourse = @takencourse+1%>
							<% @flag = 1%>
							<tr   style="background: rgba(255,255,255,0.3);">
								<td style="color:black"><%= courselist.name %></td>
								<td style="color:black"><%= courselist.prereq %></td>
								<td style="color:black"><%= courselist.hours %></td>
								<td style="color:black"><%= courselist.description %></td>
								<td style="color:black">Yes</td>
							</tr>
							<% end %>
							<% end %>
							<%if @flag !=1 %>
							<tr  >
								<td style="color:black"><%= courselist.name %></td>
								<td style="color:black"><%= courselist.prereq %></td>
								<td style="color:black"><%= courselist.hours %></td>
								<td style="color:black"><%= courselist.description %></td>
								<td style="color:black">No</td>
							</tr>
							<%end%>
							<% @flag = 0%>
							<% end %>
						</tbody>
					</table>
				</div>
				<p class='lead'>
					You are <%= (@takencourse*100)/@total%>% complete with your degree!
				</p>
				<br>
				<%end%>

				<% if @currentuser.classification == "Admin" %>
				<h1>Manage Course Catalog</h1>
				<div style="border:solid; border-color: white; scroll; height:57%; overflow-x:hidden;background: rgba(255,255,255,0.1);">
					<table  class="table table-bordered">
						<thead style="height:50px">
							<tr style="color:black">
								<th>Name</th>
								<th>Prerequisites</th>
								<th>Description</th>
								<th>Edit</th>
								<th>Delete</th>
							</tr>
						</thead>

						<tbody>
							<% @courselists.each do |courselist| %>
							<tr >
								<td style="color:black"><%= courselist.name %></td>
								<td style="color:black"><%= courselist.prereq %></td>
								<td style="color:black"><%= courselist.description %></td>
								<td style="color:black"><%= link_to 'Edit',  '#', 'data-target' => "#myModal_#{courselist.id}", 'data-toggle' => 'modal',:class => 'btn btn-default btn-md btn-block'  %>
								<div class="modal fade" id='<%= "myModal_#{courselist.id}" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
									<div class="modal-dialog">
										<div class="modal-content">
											<div class="modal-header">
												<h2 class="modal-title" id="myModalLabel" style="color: black">Edit course</h2>
											</div>
											<div class="modal-body">
												<%= render 'courselists/form', courselist: courselist %>
											</div>
										</div><!-- /.modal-content -->
									</div><!-- /.modal-dialog -->
								</div><!-- /.modal --></td>

								<td><%= link_to 'Delete', courselist,:class => 'btn btn-default btn-md btn-block', method: :delete, data: { confirm: 'Are you sure?' } %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>
				</br>
				<a href="#new-courselist" class="btn btn-outline-inverse btn-block"data-toggle="modal">New Course</a>
				<%= render :partial => 'new_courselist_modal' %>
				<%end%>
			</div>
		</div>
	</div>
</div>

app/views/student/index.html.erb
<div >
<h1>Advising Center</h1>
<% @user = User.find_by_id(session[:user_id]) %>

<h2 style="color: white">Welcome <%= @user.name%>!</h2>

</p>
<%if (@user.flag == 'false')%>
<p>
<%= button_to 'Submit Schedule', courses_path(@user.id),:class => 'btn btn-outline-inverse btn-block', method: :get %>
</p>
<%elsif (@user.flag == 'denied')%>
<p>
<%= button_to 'Resubmit Schedule', courses_path(@user.id),:class => 'btn btn-outline-inverse btn-block', method: :get %>
</p>
<%elsif (@user.flag == 'approved')%>
<p>
<%= button_to 'View Approved Schedule', @user,:class => 'btn btn-outline-inverse btn-block', method: :get %>
</p>
<%elsif (@user.flag == 'submitted')%>
<p>
<%= button_to 'View Submitted Schedule', @user,:class => 'btn btn-outline-inverse btn-block', method: :get %>
</p>
<%end%>
<p>
<% @currentuser = User.find_by_id(session[:user_id]) %>
</p>


<%if @currentuser.message == 'unread'%>
<%= link_to 'View unread messages',  '#', 'data-target' => "#newmsgModal_#{@currentuser.id}", 'data-toggle' => 'modal',  :class => "btn btn-outline-inverse btn-block" %>
<%= render 'users/new_msg_modal', user: @currentuser %>
<%else%>
<%= link_to 'View/Send messages',  '#', 'data-target' => "#newmsgModal_#{@currentuser.id}", 'data-toggle' => 'modal',:class => "btn btn-outline-inverse btn-block" %>
<%= render 'users/new_msg_modal', user: @currentuser %>
<%end%>



<p>
<%= button_to 'Appoint-Messaging', appointments_path(user: @user),:class => "btn btn-outline-inverse btn-block", method: :get %>
</p>
<p>
<% @user = User.find_by_id(session[:user_id]) %>
<%= button_to 'Course Catalog', courselists_path,:class => "btn btn-outline-inverse btn-block", method: :get %>
</p>
<p>
<%= button_to 'Logout', logout_path, :class => 'btn btn-outline-inverse btn-block', method: :delete %>
</p>
</div>

app/views/student/index.mobile.erb
<div >
<h1>Advising Center Mobile</h1>
<% @user = User.find_by_id(session[:user_id]) %>

<h2 style="color: white">Welcome <%= @user.name%>!</h2>


<%if (@user.flag == 'approved')%>
<p>
<%= button_to 'View Approved Schedule', @user,:class => 'btn btn-outline-inverse btn-block', method: :get %>
</p>
<%elsif (@user.flag == 'submitted')%>
<p>
<%= button_to 'View Submitted Schedule', @user,:class => 'btn btn-outline-inverse btn-block', method: :get %>
</p>
<%end%>
<p>
<% @currentuser = User.find_by_id(session[:user_id]) %>
</p>


<%if @currentuser.message == 'unread'%>
<%= link_to 'View unread messages',  '#', 'data-target' => "#newmsgModal_#{@currentuser.id}", 'data-toggle' => 'modal',  :class => "btn btn-outline-inverse btn-block" %>
<%= render 'users/new_msg_modal', user: @currentuser %>
<%else%>
<%= link_to 'View/Send messages',  '#', 'data-target' => "#newmsgModal_#{@currentuser.id}", 'data-toggle' => 'modal',:class => "btn btn-outline-inverse btn-block" %>
<%= render 'users/new_msg_modal', user: @currentuser %>
<%end%>



<p>
<%= button_to 'Appoint-Messaging', appointments_path(user: @user),:class => "btn btn-outline-inverse btn-block", method: :get %>
</p>
<p>
<% @user = User.find_by_id(session[:user_id]) %>
<%= button_to 'Course Catalog', courselists_path,:class => "btn btn-outline-inverse btn-block", method: :get %>
</p>
<p>
<%= button_to 'Logout', logout_path, :class => 'btn btn-outline-inverse btn-block', method: :delete %>
</p>
</div>