config/routes.rb
Advising::Application.routes.draw do
  resources :messages
  get  'message' => 'messages#index'
  post 'message' => 'messages#index'
  
  controller :messages do
    get 'message' => :index
    get  'message' => 'messages#index'
    post 'message' => 'messages#index'
  end
  
    post 'admin' => 'admin#regstudent'

  resources :appointments
  post '/createappt' => 'appointments#createAppt'
  post 'delappt' => 'appointments#destroy'
  post 'schdappt' => 'appointments#schdappt'
  get '/createappt' => 'appointments#createAppt'
  get 'delappt' => 'appointments#destroy'
  get 'schdappt' => 'appointments#schdappt'
  post 'cancappt' => 'appointments#cancappt'
  get 'viewAppts' => 'users#viewAppts'
  post 'setAppt' => 'appointments#setAppt'
  get 'denyApt' => 'appointments#deny'
  get 'approveApt' => 'appointments#approve'
  get 'deleteApt' => 'appointments#destroy'
  
  resources :courselists
  post 'getcourse' => 'courses#getcourse'
  post 'setAppt' => 'courses#setAppt'
  get 'getcourse' => 'courses#getcourse'
  post 'contactf' => 'courses#contactf'
  get 'contactf' => 'courses#contactf'

  post 'testajaxjs' => 'courses#testajaxjs'

  resources :courses
  get "student/index"
  get 'admin' => 'admin#index'
  get 'advisor' => 'advisor#index'
  get 'student' => 'student#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get "admin/index"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :users
  post 'liftFlag' => 'users#liftFlag'
  get 'liftFlag' => 'users#liftFlag'
  post 'destroy' => 'users#destroy'
  post 'denyFlag' => 'users#denyFlag'
  get 'denyFlag' => 'users#denyFlag'
  get  'messagee' => 'messages#index'#hitting this one

  controller :users do
    post 'liftFlag' => :liftFlag
    get  'liftFlag' => :liftFlag
    post 'denyFlag' => :denyFlag
    get  'denyFlag' => :denyFlag
  end
  
  resources :users do
    resources :courses
  end
  

  root 'sessions#new', as: 'advising'
  root :to =>'sessions#new'
  
  
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  default_scope order('flag ASC')
  has_secure_password
    USER_TYPES = ["Student", "Advisor"]
    has_many :courses, :dependent => :delete_all
    has_many :appointments, :foreign_key => 'stuID', :foreign_key => 'advID', :dependent => :delete_all
    has_many :messages, :foreign_key => 'to', :foreign_key => 'from', :dependent => :delete_all
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'functionalitylayout'
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  respond_to :json
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
      @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
    @user.classification = "Student"
  end

  # GET /users/1/edit
  def edit
        @users = User.all
  end
  
  def setAppt
    @currentuser = User.find_by_id(session[:user_id])
    
    
    @appts = params[:param1]
    @appte = params[:param2]
    
    if(Appointment.count(@currentuser.id) < 1)
      Appointment.create(appts: params[:param1], appte: params[:param2], stuID: @currentuser.id, advID: User.find_by_name(@currentuser.advisor).id, approved: 'pending' )
      @appt.save
      respond_to do |format|
        format.html { redirect_to courses_path(@currentuser.id) }
        format.mobile{ redirect_to courses_path(@currentuser.id) }
        format.json { render :json => { :name => @name }}
      end
    else
      @appt = Appointment.find_by_userID(@currentuser.id)
      @appt.update_attribute(:appts,@appts)
      @appt.update_attribute(:appte,@appte)
      @appt.update_attribute(:approved,'pending')
      @appt.save
      respond_to do |format|
        format.html { redirect_to courses_path(@currentuser.id) }
        format.mobile{ redirect_to courses_path(@currentuser.id) }
        format.json { render :json => { :name => @name }}
      end
    end
  end
  
  def liftFlag
    @currentuser = User.find_by_id(session[:user_id])
    @user = User.find_by_id(params[:id])
    @user.flag = 'advised'
    
    #if @user.save
    #  respond_with(@currentuser, :location => users_url);
    #end
    
      if @user.save
        redirect_to users_url
        
      end
    
  end

  def denyFlag
    @currentuser = User.find_by_id(session[:user_id])
    @user = User.find_by_id(params[:id])
    @user.flag = 'denied'
    
    
    #if @user.save
    #  respond_with(@currentuser, :location => users_url);
    #end
      if @user.save
        redirect_to users_url
        
      end
    
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @currentuser = User.find_by_id(session[:user_id])
    if @currentuser.classification != "Student"
      @user.classification = "Student"
      @user.advisor = @currentuser.name
      @user.flag = "false"
    end
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url }
        format.mobile{ redirect_to users_url }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { redirect_to admin_url }
        format.mobile{ redirect_to admin_url }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url}
        format.mobile{ redirect_to users_url}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.mobile{ render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    (Course.find_all_by_studentid(@user.id)).each do |course|
      course.destroy
    end
    (Message.find_all_by_to(@user.id)).each do |message|
      message.destroy
    end
    (Message.find_all_by_from(@user.id)).each do |message|
      message.destroy
    end
    (Appointment.find_all_by_stuID(@user.id)).each do |message|
      message.destroy
    end
    #messagee_path(@user.id,:to => @user.id,:action => 'index')
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.mobile{ redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :classification, :password, :password_confirmation, :advisor, :fname, :mi, :lname)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_user_modal.html.erb
<div id="modal-form" class="modal fade" tabindex="-1" role="dialog"
aria-labelledby="myModalLabel" aria-hidden="true" >
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-title" id="myModalLabel" style="color:black">New User</h2>
			</div>
			<div class="modal-body">
				<%= render 'users/eform', user: user %>
			</div>
		</div>
	</div>
</div>

app/views/users/_eform.html.erb
<% @currentuser = User.find_by_id(session[:user_id]) %>

<div class="form-horizontal">

	<%= form_for(user, :class=>"form-horizontal")  do |f| %>
	<div class="form-group">
		<div class="col-sm-12">
			<%= f.text_field :name, {:class=>"form-control", :placeholder=>"Username"} %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<%= f.text_field :fname, {:class=>"form-control",:placeholder=>"First Name"} %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<%= f.text_field :lname, {:class=>"form-control",:placeholder=>"Last Name"} %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<%= f.text_field :mi, {:class=>"form-control",:placeholder=>"Middle Initial"} %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
	<select id="user_advisor" name="user[advisor]" class="form-control">
				<option value="">Advisor</option>	
		<% @advisor = User.all %>
			<% @advisor.each do |list| %>
			<% @match = 0 %>
			<% if list.classification == 'Advisor'%>
			<% @match = 1 %>
			<% end %>
			<% if @match == 1 %>
			<option value="<%= list.name %>"> <%= list.name %> </option>
			<% end %>
			<% end %>
			</select>
	</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<select id="user_classification" name="user[classification]" class="form-control">
				<option value="Student">Student</option>
				<option value="Advisor">Advisor</option>
			</select>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<%= f.password_field :password, {:class=>"form-control",:placeholder=>"Password"} %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<%= f.password_field :password_confirmation, {:class=>"form-control",:placeholder=>"Confirm Password"} %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-1 col-sm-10">
			<%= f.submit "Submit",:class=>"btn btn-default" %>
		</div>
	</div>
	<% end %>
</div>

app/views/users/_form.html.erb
<% @currentuser = User.find_by_id(session[:user_id]) %>
<% @user = User.new %>

<div class="form-horizontal">

	<%= form_for(@user, :class=>"form-horizontal")  do |f| %>
	<div class="form-group">
		<div class="col-sm-12">
			<%= f.text_field :name, {:class=>"form-control", :placeholder=>"Username"} %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<%= f.text_field :fname, {:class=>"form-control",:placeholder=>"First Name"} %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<%= f.text_field :lname, {:class=>"form-control",:placeholder=>"Last Name"} %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<%= f.text_field :mi, {:class=>"form-control",:placeholder=>"Middle Initial"} %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
	<select id="user_advisor" name="user[advisor]" class="form-control">	
		<option value="">Advisor</option>
		<% @advisor = User.all %>
			<% @advisor.each do |list| %>
			<% @match = 0 %>
			<% if list.classification == 'Advisor'%>
			<% @match = 1 %>
			<% end %>
			<% if @match == 1 %>
			<option value="<%= list.name %>"> <%= list.name %> </option>
			<% end %>
			<% end %>
			</select>
	</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<select id="user_classification" name="user[classification]" class="form-control">
				<option value="Student">Student</option>
				<option value="Advisor">Advisor</option>
			</select>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<%= f.password_field :password, {:class=>"form-control",:placeholder=>"Password"} %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<%= f.password_field :password_confirmation, {:class=>"form-control",:placeholder=>"Confirm Password"} %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-1 col-sm-10">
			<%= f.submit "Submit",:class=>"btn btn-default" %>
		</div>
	</div>
	<% end %>
</div>

app/views/users/_formstudent.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" >
    <%= f.label :name, :style=>"color : #000000" %><br>
    <%= f.text_field :name, :style=>"color : #000000" %>
  </div>
  <div class="field">
    <%= f.label :fname, :style=>"color : #000000" %><br>
    <%= f.text_field :fname, :style=>"color : #000000" %>
  </div>
  <div class="field">
    <%= f.label :mi, :style=>"color : #000000" %><br>
    <%= f.text_field :mi, :style=>"color : #000000" %>
  </div>
    <div class="field">
    <%= f.label :lname, :style=>"color : #000000" %><br>
    <%= f.text_field :lname, :style=>"color : #000000" %>
  </div>
    <div class="field">
    <%= f.label :password, :style=>"color : #000000" %><br>
    <%= f.password_field :password, :style=>"color : #000000" %>
  </div>
    <div class="field">
    <%= f.label :password_confirmation, :style=>"color : #000000" %><br>
    <%= f.password_field :password_confirmation, :style=>"color : #000000" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_msg_modal.html.erb
<div id="modal-form" class="modal fade" tabindex="-1" role="dialog"
aria-labelledby="mymsgModalLabel" aria-hidden="true" >
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-title" id="mymsgModalLabel" style="color: black">Hello!</h2>
			</div>
			<div class="modal-body">
				<div class="form-horizontal">
					<table>
						<tbody>
							<%if(@currentuser.classification == 'Student')%>
							<% (Message.all).each do |message| %>
							<%if(message.from == @currentuser.id)%>
							<div class="modal-content">
								<tr>
									<td><%= "To: #{User.find_by_id(message.to).name}  From: #{@currentuser.name}"%></td>
								</tr>
								<tr>
									<td><%= message.content %></td>
								</tr>
							</div>
							<br>
							<%elsif(message.to == @currentuser.id && message.from == User.find_by_name(@currentuser.advisor).id)%>
							<div class="modal-content">
								<tr>
									<td><%= "To: #{@currentuser.name}  From: #{User.find_by_id(message.from).name}"%></td>
								</tr>
								<tr>
									<td><%= message.content %></td>
								</tr>
							</div>
							<br>
							<% end %>

							<% end %>
							<%else%>
							<% (Message.all).each do |message| %>
							<%if(message.to == @currentuser.id && message.from == user.id)%>
							<div class="modal-content">
								<tr>
									<td><%= "To: #{@currentuser.name}  From: #{User.find_by_id(message.from).name}" %></td>
								</tr>
								<tr>
									<td><%= message.content %></td>
								</tr>
							</div>
							<br>
							<%elsif(message.from == @currentuser.id && message.to == user.id)%>
							<div class="modal-content">
								<tr>
									<td><%= "To: #{User.find_by_id(message.to).name}  From: #{@currentuser.name}"%></td>
								</tr>
								<tr>
									<td><%= message.content %></td>
								</tr>
							</div>
							<br>
							<% end %>

							<% end %>
							<% end %>
						</tbody>
					</table>
				</div>
				<div class="form-horizontal">
					<%= form_tag(:class=>"form-horizontal", :role=>"form") do %>
					<div class="form-group">
						<div class="col-sm-12">
							<%= text_field_tag :content, params[:content],:class=>"form-control",:placeholder=>"Content" %>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-1 col-sm-10">
							<%= submit_tag "Submit",:class=>"btn btn-default" %>
						</div>
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/_new_msg_modal.html.erb
<% @currentuser = User.find_by_id(session[:user_id])
@user = User.find_by_id(params[:id])
@message = Message.new
%>
<div class="modal fade" id='<%= "newmsgModal_#{user.id}" %>' tabindex="-1" role="dialog" aria-labelledby="newmsgModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-title" id="newmsgModalLabel" style="color: black">Conversation</h2>
			</div>
			<div class="modal-body">

				<div class="form-horizontal">

					<%= form_for(@message) do |f| %>

					<%if(@currentuser.classification == 'Student')%>
					<%= f.hidden_field :from, :value => @currentuser.id %>
					<%= f.hidden_field :to, :value => User.find_by_name(@currentuser.advisor).id %>
					<%else%>
					<%if !@user.nil? && !@user.new_record?%>
					<%= f.hidden_field :to, :value => user.id %>
					<%= f.hidden_field :from, :value => @currentuser.id %>
					<%else%>
					<%= f.hidden_field :to, :value => user.id %>
					<%= f.hidden_field :from, :value => @currentuser.id %>

					<%end%>
					<%end%>

					<div class="form-group">
						<div class="col-sm-12">

							<div id="textdiv" class="form-control" style="overflow-y:scroll; height:250px;">
								<%if(@currentuser.classification == 'Student')%>
								<% (Message.all).each do |message| %>
								<%if(message.from == @currentuser.id)%>
								<br>
								<b><%= "To: #{User.find_by_id(message.to).name}  From: #{@currentuser.name}"%>:</b>
								<br>
								<%= message.content %>
								<br>
								<%elsif(message.to == @currentuser.id && message.from == User.find_by_name(@currentuser.advisor).id)%>
								<br>
								<b><%= "To: #{@currentuser.name}  From: #{User.find_by_id(message.from).name}"%>:</b>
								<br>
								<%= message.content %>
								<br>
								<% end %>
								<% end %>
								<%else%>
								<% (Message.all).each do |message| %>
								<%if(message.to == @currentuser.id && message.from == user.id)%>
								<br>
								<b><%= "To: #{@currentuser.name}  From: #{User.find_by_id(message.from).name}"%>:</b>
								<br>
								<%= message.content %>
								<br>
								<%elsif(message.from == @currentuser.id && message.to == user.id)%>
								<br>
								<b> <%= "To: #{User.find_by_id(message.to).name}  From: #{@currentuser.name}"%>:</b>
								<br>
								<%= message.content %>
								<br>
								<% end %>
								<% end %>
								<% end %>

							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-sm-12">
							<%= f.text_area :content, {:class=>"form-control",:placeholder=>"Content"} %>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-12">
							<%= f.submit "Submit",:class=>"btn btn-default" %>
						</div>
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/_user_modal.html.erb
<div id="modal-form" class="modal fade" tabindex="-1" role="dialog"
aria-labelledby="myModalLabel" aria-hidden="true" >
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-title" id="myModalLabel" style="color:black">New User</h2>
			</div>
			<div class="modal-body">
				<%= render :partial => 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<% @currentuser = User.find_by_id(session[:user_id]) %>
<% @courses = Course.all %>
<h1>Editing user: <%= @user.name%></h1>
<h1>You are: <%= @currentuser.name%></h1>


<% if @currentuser.classification == "Advisor" %>

<%= render 'form' %>
<h3>COURSES:</h3>
<table>
	<th>Name</th>
	<th>Hours</th>
	<th>Prereq</th>
	<% @courses.each do |course| %>
	<%if course.studentid == @user.id %>
	<tr>
		<td><%= course.name %></td>
		<td><%= course.hours %></td>
		<td><%= course.prereq %></td>
	</tr>
	<%end%>
	<%end%>
</table>
<% end %>
<% if @currentuser.classification == "Admin" %>
<%= render 'form' %>

<%if @user.classification == "Advisor"%>
<table>
<h3>STUDENTS:</h3>

<th>Name</th>
<% @users.each do |user| %>
		<% if (user.advisor == @user.name) %>
		<tr>
			<td><%= user.name %></td>
			<td><%= link_to 'Show', user %></td>
			<td><%= link_to 'Edit', edit_user_path(user) %></td>
			<td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
		<% end %>
		</table>
<%end%>

<%if @user.classification == "Student"%>
<h3>COURSES:</h3>
<table>
	<th>Name</th>
	<th>Hours</th>
	<th>Prereq</th>
	<% @courses.each do |course| %>
	<%if course.studentid == @user.id %>
	<tr>
		<td><%= course.name %></td>
		<td><%= course.hours %></td>
		<td><%= course.prereq %></td>
		
	</tr>
	<%end%>
	<%end%>
	<%end%>
</table>
<% end %>

</br>
<%= link_to 'Show', @user %> |
<%case @currentuser.classification%>
<%      when "Admin"%>
<%= link_to 'Back', admin_path() %>
<%      when "Advisor"%>
<%= link_to 'Back', advisor_path() %>
<%     else%>
<%= link_to 'Back', student_path() %>
<%     end%>

app/views/users/index.html.erb
<% if notice %>
<p id="notice">
	<%= notice %>
</p>
<% end %>

<% @currentuser = User.find_by_id(session[:user_id]) %>
<% if @currentuser.classification == 'Advisor'%>
<%if(!(session[:current_path] =~ /value/))%>

<h1>View Registration Packages</h1>
<div style="border:solid; border-color: white; scroll; height:57%; overflow-x:hidden;background: rgba(255,255,255,0.1);">
	<table  class="table table-bordered">
		<thead style="height:50px">
			<tr>
				<th>Username</th>
				<th>Status</th>
				<th>Show</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
			<tr>
				<% if (user.advisor == @currentuser.name) %>
				<td><%= user.name %></td>
				<% if (user.advisor == @currentuser.name && user.flag == 'submitted') %>
				<td>Submission Pending</td>
				<%end%>
				<% if (user.advisor == @currentuser.name && user.flag == 'false') %>
				<td>Unadvised</td>
				<%end%>
				<% if (user.advisor == @currentuser.name && user.flag == 'denied') %>
				<td>Denied</td>
				<%end%>
				<% if (user.advisor == @currentuser.name && user.flag == 'advised') %>
				<td>Advised</td>
				<%end%>
				<td><%= button_to 'Show', user,:class => 'btn btn-default btn-md btn-block', :method=> :get, :style => "color:black" %></td>
				<%end%>
				<% end %>

				<tbody>

	</table>
</div>

<%else%>

<h1>Messages for <%= @currentuser.name%></h1>
<div style="border:solid; border-color: white; scroll; height:57%; overflow-x:hidden;background: rgba(255,255,255,0.1);">
	<table  class="table table-bordered">

	<tbody>
		<th>Student</th>
		<th>Send Message</th>
		 <% @users.each do |user| %>
		<% if (user.advisor == @currentuser.name) %>
		<tr>
			<td><%= user.name %></td>
			<td><%= link_to 'View/Send message',  '#', 'data-target' => "#newmsgModal_#{user.id}", 'data-toggle' => 'modal',:class => 'btn btn-default btn-md btn-block', :style => "color:black"  %>
			<%= render 'new_msg_modal', user: user %></td>
		</tr> <% end %>
		<% end %> 
	</tbody>
	<% end %>
	<% end %>
</table>
</div>



	<% if @currentuser.classification == "Admin"%>
	<h1>Manage Users</h1>
	<div style="border:solid; border-color: white; scroll; height:57%; overflow-x:hidden;background: rgba(255,255,255,0.1);">
		<table  class="table table-bordered">
			<thead style="height:50px">
				<tr>
					<th>Unsername</th>
					<th>Classification</th>
					<th>Advisor</th>
					<th>Show</th>
					<th>Edit</th>
					<th>Destroy</th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<%if user.classification != "Admin"%>
					<td><%= user.name %></td>
					<td><%= user.classification %></td>
					<td><%= user.advisor %></td>
					<td><%= link_to 'Show', user,:class => 'btn btn-default btn-md btn-block', :style => "color:black" %></td>
					<td><%= link_to 'Edit',  '#', 'data-target' => "#myModal_#{user.id}", 'data-toggle' => 'modal',:class => 'btn btn-default btn-md btn-block', :style => "color:black"  %>
					<div class="modal fade" id='<%= "myModal_#{user.id}" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<h2 class="modal-title" id="myModalLabel" style="color: black">Edit User</h2>
								</div>
								<div class="modal-body">
									<%= render 'users/eform', user: user %>
								</div>
							</div>
						</div>
					</div></td>
					<td><%= button_to 'Destroy', destroy_path(:id => user.id,:action => :destroy), data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-md btn-block', :style => "color:black"  %></td>
					<%end%>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<br>
	<p>
		<a href="#modal-form" class="btn btn-outline-inverse btn-block"data-toggle="modal">New User</a>
	</p>
	<%= render :partial => 'user_modal' %>
	<% end %>

app/views/users/new.html.erb
w<h1>New user</h1>

<% @currentuser = User.find_by_id(session[:user_id]) %>

<% if (@currentuser.classification == "Admin") %>
	<%= render :partial => 'user_modal' %>
<% else%>
	<%= render 'formstudent' %>
<%end%>

<%= link_to 'Back', users_path %>