config/routes.rb
Advising::Application.routes.draw do
  resources :messages
  get  'message' => 'messages#index'
  post 'message' => 'messages#index'
  
  controller :messages do
    get 'message' => :index
    get  'message' => 'messages#index'
    post 'message' => 'messages#index'
  end
  
    post 'admin' => 'admin#regstudent'

  resources :appointments
  post '/createappt' => 'appointments#createAppt'
  post 'delappt' => 'appointments#destroy'
  post 'schdappt' => 'appointments#schdappt'
  get '/createappt' => 'appointments#createAppt'
  get 'delappt' => 'appointments#destroy'
  get 'schdappt' => 'appointments#schdappt'
  post 'cancappt' => 'appointments#cancappt'
  get 'viewAppts' => 'users#viewAppts'
  post 'setAppt' => 'appointments#setAppt'
  get 'denyApt' => 'appointments#deny'
  get 'approveApt' => 'appointments#approve'
  get 'deleteApt' => 'appointments#destroy'
  
  resources :courselists
  post 'getcourse' => 'courses#getcourse'
  post 'setAppt' => 'courses#setAppt'
  get 'getcourse' => 'courses#getcourse'
  post 'contactf' => 'courses#contactf'
  get 'contactf' => 'courses#contactf'

  post 'testajaxjs' => 'courses#testajaxjs'

  resources :courses
  get "student/index"
  get 'admin' => 'admin#index'
  get 'advisor' => 'advisor#index'
  get 'student' => 'student#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get "admin/index"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :users
  post 'liftFlag' => 'users#liftFlag'
  get 'liftFlag' => 'users#liftFlag'
  post 'destroy' => 'users#destroy'
  post 'denyFlag' => 'users#denyFlag'
  get 'denyFlag' => 'users#denyFlag'
  get  'messagee' => 'messages#index'#hitting this one

  controller :users do
    post 'liftFlag' => :liftFlag
    get  'liftFlag' => :liftFlag
    post 'denyFlag' => :denyFlag
    get  'denyFlag' => :denyFlag
  end
  
  resources :users do
    resources :courses
  end
  

  root 'sessions#new', as: 'advising'
  root :to =>'sessions#new'
  
  
  
  

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<% @currentuser = User.find_by_id(session[:user_id]) %>

<nav class="navbar navbar-inverse navbar-fixed-top">

	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
				<label class="navbar-brand" style="font-weight: normal" data-toggle="collapse" data-target=".navbar-collapse">Advising Center
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span></label>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<%= render 'layouts/navigation_links' %>
			</ul>
			<div class="navbar-header navbar-right">
  		<p class="navbar-text">
  		<ul><%=@currentuser.name%></ul>
  		</p>
  	</div>
		</div>
	</div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% @cuser = User.find_by_id(session[:user_id]) %>

<%case @cuser.classification%>
<%      when "Admin"%>
<p><%= button_to 'Home', admin_path(),:class => "btn btn-outline-inverse btn-block" ,method: :get %></p>
<p><%= button_to 'Manage Users', users_path(),:class => "btn btn-outline-inverse btn-block" ,method: :get %></p>
<p><%= button_to 'Manage Courses', courselists_path(),:class => "btn btn-outline-inverse btn-block" ,method: :get %></p>


<%    when "Advisor"%>
<p><%= button_to 'Home', advisor_path(),:class => "btn btn-outline-inverse btn-block",method: :get  %></p>
<p>
<%= button_to 'Manage Users', users_path(), :class => "btn btn-outline-inverse btn-block", method: :get %>
</p>
<%= button_to 'Appointments', appointments_path(), :class => "btn btn-outline-inverse btn-block", method: :get %>
</p>
<p>
<%= button_to 'View Messages', users_path("value", :value => true), :class => "btn btn-outline-inverse btn-block", method: :get %>
</p>
<p>


<%     else%>



<p><%= button_to 'Home', student_path(),:class => "btn btn-outline-inverse btn-block",method: :get  %></p>

<%if (@cuser.flag == 'approved')%>
<p>
<%= button_to 'View Approved Schedule', @cuser,:class => "btn btn-outline-inverse btn-block", method: :get %>
</p>
<%elsif (@cuser.flag == 'submitted')%>
<p>
<%= button_to 'View Submitted Schedule', @cuser,:class => "btn btn-outline-inverse btn-block", method: :get %>
</p>
<%end%>
<p>
<%= button_to 'Appoint-Messaging', appointments_path(@cuser.id),:class => "btn btn-outline-inverse btn-block", method: :get %>
</p>
<p>

<%= button_to 'Course Catalog', courselists_path,:class => "btn btn-outline-inverse btn-block", method: :get %>
</p>
<%     end%>
<p><%= button_to 'Logout',  logout_path,:class => "btn btn-outline-inverse btn-block",  method: :delete %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Advising" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Advising" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
    </header>
    <mainn role="main">
    	
       <%= render 'layouts/messages' %>
       <%= yield %>
    </mainn>
  </body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>

  <title>Mobile Version!</title>

  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css"/>
  
  <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script>
  $(document).bind("mobileinit", function () {
    	$.mobile.ajaxEnabled = false;
	});
  </script>
  <%= javascript_include_tag "jquery_ujs.js" %>
  <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>

</head>
<body>
<div data-role="page">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Advising" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Advising" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
    </header>
    <mainn role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </mainn>
  </body>
</html>

app/views/layouts/functionalitylayout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Advising" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Advising" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="bs-docs-masthead">
    <header>
    </header>
    <mainn role="main">
		<%= render 'layouts/navigation' %>
       <%= render 'layouts/messages' %>
       <%= yield %>
    </mainn>
  </body>
</html>
<style>

h1{
	margin-top: 60px;
	
}

th {
text-align: center;
font-size: 25px;
color: white;
}

 @media (min-width: 768px) {
    .bs-docs-masthead {
      padding-top: 80px;
      padding-bottom: 10%;
    }
    
.bs-docs-masthead, .bs-docs-header {
    position: absolute;
    padding: 30px 15px;
    color: #cdbfe3;
    text-align: center;
    text-shadow: 0 3px 0 rgba(0,0,0,.1);
   background: image-url("img.jpg") no-repeat fixed 100% 100%;
 }
</style>

app/views/layouts/menu.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Advising" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Advising" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="bs-docs-masthead">
    <header>
    </header>
    <mainn role="main">

       <%= render 'layouts/messages' %>
       <%= yield %>
    </mainn>
  </body>
</html>
<style>


 @media (min-width: 768px) {
    .bs-docs-masthead {
      padding-top: 0px;
      padding-bottom: 10%;
    }
</style>